export const DEFAULT_FAQS = [
  { question: "¿Cuánto cuesta un seguro de salud Sanitas?", answer: "Los seguros de salud Sanitas comienzan desde 39€/mes con Sanitas Pymes Digital para empresas. Para particulares, Sanitas Avanza (con copagos reducidos) parte desde 49€/mes y Sanitas Más Salud (sin copagos) desde 89€/mes. Los precios finales dependen de la edad, coberturas seleccionadas y modalidad de pago. Si eliges pago anual, obtienes un 4% de descuento adicional." },
  { question: "¿Qué incluye Blua de Sanitas y cómo funciona?", answer: "Blua es la plataforma digital de salud de Sanitas, incluida GRATIS para siempre en todos los seguros. Ofrece: videoconsulta con médicos de todas las especialidades, evaluador de síntomas con inteligencia artificial, programas de salud digital (embarazo, nutrición, entrenador personal, salud infantil), servicio de psicología digital, fisioterapia digital y chequeos de salud preventivos. Se accede desde la app Blua de Sanitas." },
  { question: "¿Puedo eliminar los periodos de carencia al contratar Sanitas?", answer: "Sí. Si llevas al menos 1 año con una póliza de salud completa en otra compañía en España, puedes eliminar las carencias de tu nueva póliza Sanitas (excepto parto). Solo necesitas aportar una copia de las condiciones particulares (o tarjeta sanitaria con fecha de alta) y el último recibo o justificante de pago de esa póliza. Puedes hacerlo durante el proceso de contratación o justo después." },
  { question: "¿Cuántos médicos tiene el cuadro médico de Sanitas?", answer: "El cuadro médico de Sanitas es uno de los más amplios de España, con más de 57.000 profesionales médicos, 4.500 centros médicos, 5 hospitales propios, 25 centros médicos propios, 10 centros de rehabilitación avanzada y 7 centros de bienestar. Ofrece cobertura en todas las provincias de España." },
  { question: "¿Qué ventajas fiscales tiene un seguro para autónomos?", answer: "Los autónomos pueden desgravarse la prima del seguro de salud en la declaración de la renta (IRPF). La deducción máxima es de 500€ anuales por persona asegurada, hasta un máximo de 1.500€ si incluyen cónyuge e hijos menores de 25 años. Esto convierte al seguro de salud en uno de los gastos más rentables para un profesional independiente." },
  { question: "¿Sanitas tiene seguros sin copagos?", answer: "Sí. Sanitas Más Salud es nuestro seguro sin copagos más completo. Incluye acceso ilimitado a medicina primaria, todas las especialidades médicas, hospitalización completa, urgencias 24h y la app Blua gratis para siempre. Es ideal para quienes quieren disfrutar de la sanidad privada sin preocuparse por pagos adicionales en cada visita." },
  { question: "¿Cómo contrato un seguro Sanitas?", answer: "Puedes contratar tu seguro Sanitas de varias formas: llamándonos al 624 21 73 23, enviándonos un WhatsApp, o rellenando el formulario de contacto en esta web para que te llamemos gratis en menos de 5 minutos. Te asesoramos sin compromiso." },
  { question: "¿Sanitas tiene seguro dental? ¿Qué incluye?", answer: "Sí, Sanitas ofrece dos modalidades: Sanitas Dental Milenium (con acceso a más de 5.200 clínicas, radiografías y tratamientos incluidos) y Sanitas Dental Premium (con coberturas ampliadas como implantes, ortodoncia y blanqueamiento). Ambos incluyen limpieza dental anual gratuita y revisiones periódicas." },
];
